server:
  port: 8084

spring:
  application:
    name: rating
  datasource:
    url: jdbc:postgresql://localhost:5432/rating
    username: postgres
    password: postgres

ride:
  name: ride
  path: /api/v1/rides

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
