server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: driver
          uri: lb://driver
          predicates:
            - Path=/api/v1/drivers/**
        - id: passenger
          uri: lb://passenger
          predicates:
            - Path=/api/v1/passengers/**
        - id: ride
          uri: lb://ride
          predicates:
            - Path=/api/v1/rides/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payments/**
        - id: rating
          uri: lb://rating
          predicates:
            - Path=/api/v1/ratings/**

logging:
  level:
    web: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
