server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ride
  kafka:
    bootstrap-servers: localhost:9092


payment:
  url: localhost:8083
  name: payment
  pay_uri: /api/v1/payment/ride