server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ride
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
#      key-deserializer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer