server:
  port: 8082

spring:
  application:
    name: ride
  data:
    mongodb:
      host: localhost
      database: ride
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.modsen.ride: debug
