server:
  port: 8082

spring:
  application:
    name: ride
  data:
    mongodb:
      host: localhost
      database: ride
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092

driver:
  name: driver
  url: localhost:8081
  getById: /api/v1/drivers/{id}
  update: /api/v1/drivers/{id}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.modsen.ride: debug
