server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      database: ride
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092


payment:
  url: localhost:8083
  name: payment
  pay_uri: /api/v1/payment/ride