server:
  port: 8083

spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    function:
      definition: processRidePayment
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        processRidePayment-in-0:
          destination: ride-payment
          group: payment-service
        processRidePayment-out-0:
          destination: payment-result

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
