server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: prometheus
