name: Maven CI/CD

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test project with Maven
        run: ./mvnw clean verify
  generate-jacoco-report:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Generate Jacoco Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: jacoco-report/target/site/jacoco-aggregate/jacoco.csv
          badges-directory: jacoco-report/target/site/jacoco-aggregate/badges

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: jacoco-report/target/site/jacoco-aggregate